---
title: "Treeshap (R) versus SHAP (python)"
author: "M Loecher"
date: "13 11 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ranger)
library(treeshap)
library(RColorBrewer)

## Add an alpha value to a colour
add.alpha <- function(col, alpha=1){
  if(missing(col))
    stop("Please provide a vector of colours.")
  apply(sapply(col, col2rgb)/255, 2, 
                     function(x) 
                       rgb(x[1], x[2], x[3], alpha=alpha))  
}
```

### Data 

```{r}
titanic = read.csv("https://raw.githubusercontent.com/markusloecher/shap/master/Explore/titanicnoMissingAge.csv")
xCols = c('Age', 'Pclass','Sex', 'PassengerId')
data_train = titanic[,c("Survived", xCols)]
```


### Random forest in `ranger`

```{r}
set.seed(0)
rf_model = ranger(Survived ~ Age + Pclass + Sex +PassengerId, data = data_train, mtry=2, num.trees = 100, max.depth = 50)
```

### Treeshap

```{r}
unified <- ranger.unify(rf_model, data_train)
sum(!is.na(unified$`Quality/Score`))#just the leaves ?
sum(!is.na(unified$Split))
```
```{r, cache=TRUE}
treeshap_values <- treeshap(unified, data_train)
```

### Compare with Lundberg's SHAP library:

```{r}
shap_values_titanic = read.csv("https://raw.githubusercontent.com/markusloecher/shap/master/Explore/shap_values_titanic.csv", header=FALSE)
colnames(shap_values_titanic) = xCols
```

```{r, fig.width=9,fig.height=9}
mypalette<- add.alpha(brewer.pal(4,"Dark2"),0.5)
names(mypalette) = xCols
par(mfrow=c(2,2))
for (v in xCols ){
  plot(treeshap_values[,v]/100, shap_values_titanic[,v], main = v, ylab = "python SHAP", xlab = "treeshap", col = mypalette[v],pch=20);grid()
  xy= cbind.data.frame(treeshap=treeshap_values[,v]/100, lundberg=shap_values_titanic[,v])
  fit = lm(lundberg ~  treeshap,data = xy);SumFit =summary(fit)
  abline(fit,col=2)
  cat("Residual Stderr for ",v, ":", round(SumFit$sigma,3),"\n")
}
```

### Natural Variations in SHAP values

```{r}
shap_values_sd = read.csv("https://raw.githubusercontent.com/markusloecher/shap/master/Explore/ShapVals_sd.csv", header=FALSE)
colnames(shap_values_sd) = xCols
shap_values_mu = read.csv("https://raw.githubusercontent.com/markusloecher/shap/master/Explore/ShapVals_mu.csv", header=FALSE)
colnames(shap_values_mu) = xCols
```


```{r, fig.width=9,fig.height=9}
mypalette<- add.alpha(brewer.pal(4,"Dark2"),0.5)
names(mypalette) = xCols
par(mfrow=c(2,2))
for (v in xCols ){
  plot(shap_values_mu[,v], shap_values_sd[,v], main = v, ylab = "stdev SHAP", xlab = "mean SHAP", col = mypalette[v],pch=20, ylim = c(0,0.03),xlim = c(-0.25,0.6));grid()
}
```

